/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
===========================================================================*/
#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif

#ifndef EDITOR_API
#define EDITOR_API DLL_IMPORT
#endif

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern EDITOR_API FName EDITOR_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif

AUTOGENERATE_NAME(Build)
AUTOGENERATE_NAME(CreateMaterial)

#ifndef NAMES_ONLY


class EDITOR_API UAnimNotifyProps : public UObject
{
public:
    class UAnimNotify* Notify;
    DECLARE_CLASS(UAnimNotifyProps,UObject,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(UAnimNotifyProps)
};

#define UCONST_RF_Standalone 0x00080000

struct UMaterialFactory_eventCreateMaterial_Parms
{
    class UObject* InOuter;
    FString InPackage;
    FString InGroup;
    FString InName;
    class UMaterial* ReturnValue;
};
class EDITOR_API UMaterialFactory : public UObject
{
public:
    FStringNoInit Description;
    DECLARE_FUNCTION(execConsoleCommand);
    class UMaterial* eventCreateMaterial(class UObject* InOuter, const FString& InPackage, const FString& InGroup, const FString& InName)
    {
        UMaterialFactory_eventCreateMaterial_Parms Parms;
        Parms.ReturnValue=0;
        Parms.InOuter=InOuter;
        Parms.InPackage=InPackage;
        Parms.InGroup=InGroup;
        Parms.InName=InName;
        ProcessEvent(FindFunctionChecked(EDITOR_CreateMaterial),&Parms);
        return Parms.ReturnValue;
    }
    DECLARE_CLASS(UMaterialFactory,UObject,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(UMaterialFactory)
};


struct UBrushBuilder_eventBuild_Parms
{
    BITFIELD ReturnValue;
};
class EDITOR_API UBrushBuilder : public UObject
{
public:
    FStringNoInit BitmapFilename;
    FStringNoInit ToolTip;
    TArrayNoInit<FVector> Vertices;
    TArrayNoInit<FBuilderPoly> Polys;
    FName Group;
    BITFIELD MergeCoplanars:1 GCC_PACK(4);
    DECLARE_FUNCTION(execPolyEnd);
    DECLARE_FUNCTION(execPolyi);
    DECLARE_FUNCTION(execPolyBegin);
    DECLARE_FUNCTION(execPoly4i);
    DECLARE_FUNCTION(execPoly3i);
    DECLARE_FUNCTION(execVertex3f);
    DECLARE_FUNCTION(execVertexv);
    DECLARE_FUNCTION(execBadParameters);
    DECLARE_FUNCTION(execGetPolyCount);
    DECLARE_FUNCTION(execGetVertex);
    DECLARE_FUNCTION(execGetVertexCount);
    DECLARE_FUNCTION(execEndBrush);
    DECLARE_FUNCTION(execBeginBrush);
    BITFIELD eventBuild()
    {
        UBrushBuilder_eventBuild_Parms Parms;
        Parms.ReturnValue=0;
        ProcessEvent(FindFunctionChecked(EDITOR_Build),&Parms);
        return Parms.ReturnValue;
    }
    DECLARE_CLASS(UBrushBuilder,UObject,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(UBrushBuilder)
};

#endif

AUTOGENERATE_FUNCTION(UMaterialFactory,-1,execConsoleCommand);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execPolyEnd);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execPolyi);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execPolyBegin);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execPoly4i);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execPoly3i);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execVertex3f);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execVertexv);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execBadParameters);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execGetPolyCount);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execGetVertex);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execGetVertexCount);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execEndBrush);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execBeginBrush);

#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif

#if SUPPORTS_PRAGMA_PACK
#pragma pack (pop)
#endif

#if __STATIC_LINK
#ifndef EDITOR_NATIVE_DEFS
#define EDITOR_NATIVE_DEFS

DECLARE_NATIVE_TYPE(Editor,UAnimNotifyProps);
DECLARE_NATIVE_TYPE(Editor,UMaterialFactory);
DECLARE_NATIVE_TYPE(Editor,UBrushBuilder);

#define AUTO_INITIALIZE_REGISTRANTS_EDITOR \
	UStripSourceCommandlet::StaticClass(); \
	UPkgCommandlet::StaticClass(); \
	UBitMatrix::StaticClass(); \
	UBitArray::StaticClass(); \
	UStaticMeshExporterT3D::StaticClass(); \
	UStaticMeshFactory::StaticClass(); \
	UEditInfo::StaticClass(); \
	UPrefab::StaticClass(); \
	UTransactor::StaticClass(); \
	UTransBuffer::StaticClass(); \
	UAnimNotifyProps::StaticClass(); \
	UEditorEngine::StaticClass(); \
	UMaterialFactory::StaticClass(); \
	GNativeLookupFuncs[Lookup++] = &FindEditorUMaterialFactoryNative; \
	UFontFactory::StaticClass(); \
	UTextureFactory::StaticClass(); \
	UTextureExporterDDS::StaticClass(); \
	UTextureExporterTGA::StaticClass(); \
	UTextureExporterBMP::StaticClass(); \
	UTextureExporterPCX::StaticClass(); \
	UPrefabFactory::StaticClass(); \
	USoundFactory::StaticClass(); \
	UModelFactory::StaticClass(); \
	UPolysFactory::StaticClass(); \
	ULevelFactory::StaticClass(); \
	UClassFactoryUC::StaticClass(); \
	UTextureFactoryNew::StaticClass(); \
	UClassFactoryNew::StaticClass(); \
	ULevelFactoryNew::StaticClass(); \
	UPrefabExporterT3D::StaticClass(); \
	ULevelExporterSTL::StaticClass(); \
	ULevelExporterT3D::StaticClass(); \
	UModelExporterT3D::StaticClass(); \
	UPolysExporterT3D::StaticClass(); \
	UClassExporterUC::StaticClass(); \
	UClassExporterH::StaticClass(); \
	USoundExporterWAV::StaticClass(); \
	UTextBufferExporterTXT::StaticClass(); \
	UChecksumPackageCommandlet::StaticClass(); \
	UUpdateUModCommandlet::StaticClass(); \
	UMasterCommandlet::StaticClass(); \
	UMapConvertCommandlet::StaticClass(); \
	UMakeCommandlet::StaticClass(); \
	UDXTConvertCommandlet::StaticClass(); \
	URearrangeIntCommandlet::StaticClass(); \
	UMergeIntCommandlet::StaticClass(); \
	UCompareIntCommandlet::StaticClass(); \
	UDumpIntCommandlet::StaticClass(); \
	UCutdownContentCommandlet::StaticClass(); \
	UConvertMaterialCommandlet::StaticClass(); \
	UDataRipCommandlet::StaticClass(); \
	UPackageFlagCommandlet::StaticClass(); \
	UCheckUnicodeCommandlet::StaticClass(); \
	UConformCommandlet::StaticClass(); \
	UBrushBuilder::StaticClass(); \
	GNativeLookupFuncs[Lookup++] = &FindEditorUBrushBuilderNative; \
	UBatchExportCommandlet::StaticClass(); \
	UAnalyzeContentCommandlet::StaticClass(); \
	UTrueTypeFontFactory::StaticClass(); \

#endif // Editor_NATIVE_DEFS

#ifdef NATIVES_ONLY
NATIVE_INFO(UMaterialFactory) GEditorUMaterialFactoryNatives[] = 
{ 
	MAP_NATIVE(UMaterialFactory,execConsoleCommand)
	{NULL,NULL}
};
IMPLEMENT_NATIVE_HANDLER(Editor,UMaterialFactory);

NATIVE_INFO(UBrushBuilder) GEditorUBrushBuilderNatives[] = 
{ 
	MAP_NATIVE(UBrushBuilder,execPolyEnd)
	MAP_NATIVE(UBrushBuilder,execPolyi)
	MAP_NATIVE(UBrushBuilder,execPolyBegin)
	MAP_NATIVE(UBrushBuilder,execPoly4i)
	MAP_NATIVE(UBrushBuilder,execPoly3i)
	MAP_NATIVE(UBrushBuilder,execVertex3f)
	MAP_NATIVE(UBrushBuilder,execVertexv)
	MAP_NATIVE(UBrushBuilder,execBadParameters)
	MAP_NATIVE(UBrushBuilder,execGetPolyCount)
	MAP_NATIVE(UBrushBuilder,execGetVertex)
	MAP_NATIVE(UBrushBuilder,execGetVertexCount)
	MAP_NATIVE(UBrushBuilder,execEndBrush)
	MAP_NATIVE(UBrushBuilder,execBeginBrush)
	{NULL,NULL}
};
IMPLEMENT_NATIVE_HANDLER(Editor,UBrushBuilder);

#endif // NATIVES_ONLY
#endif // __STATIC_LINK

#ifdef VERIFY_CLASS_SIZES
VERIFY_CLASS_SIZE_NODIE(UAnimNotifyProps)
VERIFY_CLASS_SIZE_NODIE(UMaterialFactory)
VERIFY_CLASS_SIZE_NODIE(UBrushBuilder)
#endif // VERIFY_CLASS_SIZES
